// Generated by CoffeeScript 1.6.3
(function() {
  require(['$api/models', '$views/list#List', '$views/image#Image'], function(models, List, Image) {
    var playNextTrack,
      _this = this;
    console.log('spotify loaded...');
    playNextTrack = function() {
      return $.getJSON('http://localhost:8080/api/next-track', function(track) {
        var _this = this;
        return models.Track.fromURI(track.uri).load('name', 'artists').done(function(track) {
          $('#track-image').attr('src', track.image);
          $('#track-name').text(track.name);
          $('#track-artist').text(track.artists[0].name);
          return models.player.playTrack(track);
        });
      });
    };
    models.player.addEventListener('change', function(e) {
      console.log(e.data);
      if ((e.data.playing === false) && (e.data.track === null)) {
        console.log('detected end of track, playing next');
        return playNextTrack();
      }
    });
    return playNextTrack();
  });

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
